### ISSUE TITLE
getting a error while installation via pip

### ISSUE THREAD

**Issue by Ekanssh** [devakira/py-rpc#3]
``Collecting pyrpc
  Using cached https://files.pythonhosted.org/packages/d4/29/078873b3f7763f4cf636007b168657404cc070a41f2586655a45ca0fff2b/pyRpc-0.3.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\INDIA\AppData\Local\Temp\pip-install-6d1qq7mk\pyrpc\setup.py", line 12, in <module>
        execfile('pyRpc/_version.py', {}, ctx)
    NameError: name 'execfile' is not defined
Command "python setup.py egg_info" failed with error code 1 in `C:\Users\INDIA\AppData\Local\Temp\pip-install-6d1qq7mk\pyrpc\``

This is the error.

**Comment by zspri** [comment]
This project is not currently being maintained. Please use the alternative mentioned in the README instead.
